ci(build): actually vendor dependencies
We will shall not speak about this or why it's on the `linters` branch. (I was really tired) My next commit is adding back markdownlint.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -44,17 +44,44 @@ jobs:
         with:
           global-json-file: global.json
       - name: Restore
-        run: dotnet restore SnapX.sln
+        run: dotnet restore --packages ./vendor SnapX.sln
       - name: Cache .NET NuGet packages
         uses: actions/cache@v4
         with:
-          path: |
-            ~/.nuget/packages
-            C:\Users\runner\.nuget\packages
+          path: vendor
           key: ${{ runner.os }}-${{ runner.arch }}-nuget-${{ hashFiles('**/*.csproj') }}
           restore-keys: |
             ${{ runner.os }}-nuget-
-      # Needed for offline building :3
+      - name: 🛠 Generate NuGet.config and Directory.Build.props
+        run: |
+          cat > NuGet.config <<EOF
+              <?xml version="1.0" encoding="utf-8"?>
+              <configuration>
+              <packageSources>
+              <clear />
+              <add key="Local" value="vendor" />
+              </packageSources>
+              </configuration>
+          EOF
+      - name: 🛠 Ensure RestorePackagesPath in Directory.Build.props
+        run: |
+          FILE="Directory.Build.props"
+          PATH_NODE="//Project/PropertyGroup/RestorePackagesPath"
+
+          # If file exists and node is missing, insert it
+          if [ -f "$FILE" ]; then
+            if ! xmlstarlet sel -t -v "$PATH_NODE" "$FILE" 2>/dev/null | grep -q .; then
+              echo "🔧 Inserting <RestorePackagesPath>vendor</RestorePackagesPath>..."
+              xmlstarlet ed --inplace \
+                -s "//Project/PropertyGroup[1]" -t elem -n "RestorePackagesPath" -v "vendor" \
+                "$FILE"
+            else
+              echo "✅ RestorePackagesPath already set."
+            fi
+          else
+            echo "❌ Directory.Build.props does not exist. Cannot insert RestorePackagesPath for Vendored build. Build will FAIL."
+            exit 1
+          fi
       - name: Upload Source With Dependencies
         if: matrix.configuration == 'Debug' && runner.os == 'Linux'
         uses: actions/upload-artifact@v4
@@ -62,7 +89,6 @@ jobs:
           name: SnapX-Vendored-Source-${{ runner.arch }}
           path: .
           include-hidden-files: false
-          compression-level: 9
       - name: Ensure commit message is compliant (conventional commits via commitlint)
         if: matrix.configuration == 'Debug' && runner.os == 'Linux' && runner.arch == 'X64'
         uses: wagoid/commitlint-github-action@v6
